// import { SessionProvider, useSession } from "next-auth/react";
import "./globals.css";
import { Inter } from "next/font/google";
import { AbcdP } from "@/context/auth";
import { root } from "postcss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
 
  return (
    <>
      <html lang="en">
       
        <AbcdP>
          <body className={inter.className}>{children}</body>
        </AbcdP>
       
      </html>
    </>
  );
}
