// import { SessionProvider, useSession } from "next-auth/react";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getSession(headers().get("cookie") ?? "");

  return (
    <ClerkProvider {...pageProps}>
    <html lang="en">
     
        <body className={inter.className}>{children}</body>
   
    </html>
    </ClerkProvider>
  );
}
